"""Permissions: the capability catalogue (M4.1, ADR 0010), the Guardian (M4.2, ADR 0011) and the
birth of authorizations from approvals (M4.3, ADR 0012)."""

from ela.permissions.authorizations import (
    CHECKS,
    DEFAULT_AUTHORIZATION_TTL,
    MAX_AUTHORIZATION_TTL,
    Check,
    authorization_from_approval,
)
from ela.permissions.capabilities import (
    CORE_ECHO,
    DEFAULT_NOTES_SCOPE,
    MAX_LISTEN_SECONDS,
    MAX_RISK,
    MODEL_COMPLETE,
    PERCEPTION_CAPTURE_SCREEN,
    PERCEPTION_LISTEN,
    PHASE_10_INTRODUCED_AT,
    SCHEMA_VALIDATOR,
    V01_INTRODUCED_AT,
    WORKSPACE_WRITE_NOTE,
    CapabilityRegistry,
    catalogue_v01,
    check_capability,
    core_echo,
    is_valid_scope_entry,
    model_complete,
    perception_capture_screen,
    perception_listen,
    production_catalogue,
    validate_arguments,
    workspace_write_note,
)
from ela.permissions.errors import (
    ApprovalMismatchError,
    CapabilityNotFound,
    InvalidArgumentsError,
    InvalidCapabilityError,
    PermissionsError,
    RiskNotAllowedError,
)
from ela.permissions.guardian import (
    DEFAULT_DECISION_TTL,
    GUARDIAN_ACTOR,
    MAX_DECISION_TTL,
    POLICY_VERSION,
    RISK_POLICY,
    PermissionGuardian,
    Rule,
)
from ela.permissions.scope import scope_covers, targets_of, within_scope

__all__ = [
    "CHECKS",
    "CORE_ECHO",
    "DEFAULT_AUTHORIZATION_TTL",
    "DEFAULT_DECISION_TTL",
    "DEFAULT_NOTES_SCOPE",
    "GUARDIAN_ACTOR",
    "MAX_AUTHORIZATION_TTL",
    "MAX_DECISION_TTL",
    "MAX_RISK",
    "MODEL_COMPLETE",
    "MAX_LISTEN_SECONDS",
    "PERCEPTION_CAPTURE_SCREEN",
    "PERCEPTION_LISTEN",
    "PHASE_10_INTRODUCED_AT",
    "POLICY_VERSION",
    "RISK_POLICY",
    "SCHEMA_VALIDATOR",
    "V01_INTRODUCED_AT",
    "WORKSPACE_WRITE_NOTE",
    "ApprovalMismatchError",
    "CapabilityNotFound",
    "CapabilityRegistry",
    "Check",
    "InvalidArgumentsError",
    "InvalidCapabilityError",
    "PermissionGuardian",
    "PermissionsError",
    "RiskNotAllowedError",
    "Rule",
    "authorization_from_approval",
    "catalogue_v01",
    "check_capability",
    "core_echo",
    "is_valid_scope_entry",
    "model_complete",
    "perception_capture_screen",
    "perception_listen",
    "production_catalogue",
    "scope_covers",
    "targets_of",
    "validate_arguments",
    "within_scope",
    "workspace_write_note",
]
