"""The fingerprint of what ELA can do, and the alarm it is (M17.2 dec. I; ADR 0044).

Fase 17 has a fixed rule — *every milestone that adds a capability adds its view* — and this is
what makes it fail instead of being remembered: ``apps/command-center/capabilities.txt`` is
derived from ``production_catalogue()`` and compared byte for byte at every ``make check``.

What the file proves and what it does not is written in the file itself, and asserted here: it is
an alarm, not a demonstration. And a derivation that stopped deriving — a catalogue that answered
nothing — must **fail**, not pass in silence: that is the shape of the two alarms of dec. C.
"""

from __future__ import annotations

import importlib.util
import shutil
import sys
from functools import cache
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[2]
COMMAND_CENTER = ROOT / "apps" / "command-center"
SCRIPT = ROOT / "scripts" / "generate_command_center.py"
COMMAND = "uv run python scripts/generate_command_center.py"


@cache
def generator() -> ModuleType:
    """The script, loaded by path: ``scripts/`` is not a package (as ``tests/design`` does)."""
    spec = importlib.util.spec_from_file_location("generate_command_center", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def copy_of_the_folder(tmp_path: Path) -> Path:
    target = tmp_path / "command-center"
    shutil.copytree(COMMAND_CENTER, target)
    return target


def test_the_fingerprint_is_what_the_generator_produces() -> None:
    """Byte for byte. A capability that came or went without an answer fails here."""
    written = (COMMAND_CENTER / generator().DERIVED).read_bytes()

    assert written == generator().render(), f"stale: run `{COMMAND}`"


def test_it_says_of_itself_what_it_is_and_what_it_is_not() -> None:
    """The header must not claim more than the file knows: none of today's capabilities has a
    view of its own, and a file that said «each has its view» would be born false."""
    header = (COMMAND_CENTER / generator().DERIVED).read_text(encoding="utf-8")

    assert "GENERATED by scripts/generate_command_center.py" in header
    assert "ALLARME, non una dimostrazione" in header
    assert "nel documento\n# della milestone" in header, "the answer goes in the milestone"


def test_the_fingerprint_names_the_capabilities_the_core_builds() -> None:
    """The source is the catalogue and nothing else: no hand-written list, no exemption."""
    from ela.permissions import production_catalogue

    listed = [
        line
        for line in (COMMAND_CENTER / generator().DERIVED).read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]

    assert listed == [spec.id for spec in production_catalogue().specs()]


def test_a_capability_nobody_listed_makes_it_stale(monkeypatch: pytest.MonkeyPatch) -> None:
    """The failure the rule exists to produce, with a catalogue that has one more."""
    module = generator()
    today = module.capabilities()
    monkeypatch.setattr(module, "capabilities", lambda: (*today, "a.new.thing"))

    assert module.stale(COMMAND_CENTER)


def test_a_catalogue_that_answers_nothing_fails_instead_of_passing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The alarm of the empty derivation (dec. C, applied here): a fingerprint of nothing would
    be a check that can never fail again."""
    import ela.permissions.capabilities as source

    monkeypatch.setattr(source, "production_catalogue", lambda: _Empty())

    with pytest.raises(ValueError, match="no capability"):
        generator().capabilities()


class _Empty:
    """A catalogue with nothing in it: what the alarm above is about."""

    def specs(self) -> tuple[object, ...]:
        return ()


def test_check_is_quiet_on_the_tree(capsys: pytest.CaptureFixture[str]) -> None:
    assert generator().main(["--check"]) == 0
    assert "up to date" in capsys.readouterr().out


def test_check_notices_a_fingerprint_touched_by_hand_and_never_writes(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    folder = copy_of_the_folder(tmp_path)
    path = folder / generator().DERIVED
    path.write_bytes(path.read_bytes().replace(b"core.echo\n", b""))

    assert generator().main(["--check", "--root", str(folder)]) == 1
    assert "stale" in capsys.readouterr().out
    assert b"core.echo" not in path.read_bytes(), "--check must not write"

    assert generator().main(["--root", str(folder)]) == 0
    assert not generator().stale(folder)


def test_a_fingerprint_that_is_not_there_is_stale(tmp_path: Path) -> None:
    folder = copy_of_the_folder(tmp_path)
    (folder / generator().DERIVED).unlink()

    assert generator().stale(folder)
