"""Tools and verifiers: the implementations of the capabilities of §29 and their checks (M5.1,
ADR 0013; M5.2, ADR 0014).

A tool executes under a :class:`~ela.domain.PermissionDecision` it receives as data and never
sees the Guardian; the only module that calls a tool is the executor (rule 16). A verifier
checks the world against the success conditions of a step after the tool ran, is a separate
object from the tool by construction, and writes nothing (rule 18). Where a note path leads is
classified once, in :mod:`ela.tools.paths`, for both.
"""

from ela.tools.base import ARGUMENTS_INVALID, Outcome, Tool, check_decision
from ela.tools.captures import (
    CAPTURE_CODES,
    CAPTURE_MALFORMED,
    CAPTURE_MISSING,
    CAPTURE_NAME_INVALID,
    CAPTURE_NOT_REGULAR,
    CAPTURE_UNREADABLE,
    Capture,
    CaptureProblem,
    Retained,
    Size,
    is_capture_name,
    png_size,
)
from ela.tools.echo import CORE_ECHO, ECHO_TOOL_NAME, EchoTool
from ela.tools.errors import (
    NotIdempotentError,
    SilentVerifierError,
    ToolNotFound,
    ToolsError,
    VerifierNotFound,
)
from ela.tools.listen import LISTEN_TOOL_NAME, PERCEPTION_LISTEN, ListenTool
from ela.tools.model import MODEL_COMPLETE, MODEL_TOOL_NAME, ModelCompleteTool
from ela.tools.notes import (
    DIRECTORY_MODE,
    FILE_MODE,
    IO_ERROR,
    NOTES_TOOL_NAME,
    WORKSPACE_WRITE_NOTE,
    WriteNoteTool,
)
from ela.tools.paths import (
    PATH_CODES,
    PATH_INVALID,
    PATH_IS_DIRECTORY,
    PATH_MISSING,
    PATH_NOT_REGULAR,
    PATH_OUTSIDE_WORKSPACE,
    PATH_SYMLINK,
    PATH_UNREACHABLE,
    PathProblem,
    classify,
    is_relative_note_path,
    resolve_workspace,
)
from ela.tools.registry import (
    ToolRegistry,
    VerifierRegistry,
    node_tools,
    production_tools,
    production_verifiers,
    tools_v01,
    verifiers_v01,
)
from ela.tools.screen import (
    PERCEPTION_CAPTURE_SCREEN,
    SCREEN_CAPTURE_FAILED,
    SCREEN_NOT_OBSERVABLE,
    SCREEN_PERMISSION_DENIED,
    SCREEN_STORE_FULL,
    SCREEN_TIMEOUT,
    SCREEN_TOOL_NAME,
    SCREEN_UNSUPPORTED,
    CaptureScreenTool,
    CaptureStore,
)
from ela.tools.screen_text import (
    PERCEPTION_READ_SCREEN_TEXT,
    TEXT_LANGUAGE_UNSUPPORTED,
    TEXT_RECOGNITION_FAILED,
    TEXT_TIMEOUT,
    TEXT_TOOL_NAME,
    TEXT_UNSUPPORTED,
    ReadScreenTextTool,
)
from ela.tools.settings import CaptureSettings, WorkspaceSettings, default_workspace_dir
from ela.tools.verifiers import (
    CAPTURE_DECLARED_MISMATCH,
    CAPTURE_EXISTS,
    CAPTURE_MATCHES,
    CAPTURE_VERIFIER_NAME,
    ECHO_MESSAGE_MATCHES,
    ECHO_MESSAGE_MISMATCH,
    ECHO_VERIFIER_NAME,
    MODEL_ANSWERED,
    MODEL_MISROUTED,
    MODEL_NO_ANSWER,
    MODEL_ROUTED_AS_ASKED,
    MODEL_UNACCOUNTED,
    MODEL_VERIFIER_NAME,
    NOTE_CONTENT_MATCHES,
    NOTE_CONTENT_MISMATCH,
    NOTE_EXISTS,
    NOTE_UNREADABLE,
    NOTES_VERIFIER_NAME,
    CaptureScreenVerifier,
    EchoVerifier,
    ListenVerifier,
    ModelCompleteVerifier,
    ReadScreenTextVerifier,
    SpeakVerifier,
    WriteNoteVerifier,
)
from ela.tools.verify import COMMON_FAILURE_CODES, VERIFICATION_ARGUMENTS_INVALID, Verifier
from ela.tools.voice import (
    VOICE_DISABLED,
    VOICE_FAILED,
    VOICE_SPEAK,
    VOICE_TIMEOUT,
    VOICE_TOOL_NAME,
    VOICE_UNSUPPORTED,
    SpeakTool,
    digest_of,
)
from ela.tools.voice_online import (
    VOICE_ONLINE_TOOL_NAME,
    VOICE_SPEAK_ONLINE,
    SpeakOnlineTool,
)

__all__ = [
    "ListenVerifier",
    "PERCEPTION_LISTEN",
    "ListenTool",
    "LISTEN_TOOL_NAME",
    "ARGUMENTS_INVALID",
    "CAPTURE_CODES",
    "CAPTURE_DECLARED_MISMATCH",
    "CAPTURE_EXISTS",
    "CAPTURE_MALFORMED",
    "CAPTURE_MATCHES",
    "CAPTURE_MISSING",
    "CAPTURE_NAME_INVALID",
    "CAPTURE_NOT_REGULAR",
    "CAPTURE_UNREADABLE",
    "CAPTURE_VERIFIER_NAME",
    "COMMON_FAILURE_CODES",
    "CORE_ECHO",
    "DIRECTORY_MODE",
    "ECHO_MESSAGE_MATCHES",
    "ECHO_MESSAGE_MISMATCH",
    "ECHO_TOOL_NAME",
    "ECHO_VERIFIER_NAME",
    "FILE_MODE",
    "IO_ERROR",
    "MODEL_ANSWERED",
    "MODEL_COMPLETE",
    "MODEL_MISROUTED",
    "MODEL_NO_ANSWER",
    "MODEL_ROUTED_AS_ASKED",
    "MODEL_TOOL_NAME",
    "MODEL_UNACCOUNTED",
    "MODEL_VERIFIER_NAME",
    "NOTES_TOOL_NAME",
    "NOTES_VERIFIER_NAME",
    "NOTE_CONTENT_MATCHES",
    "NOTE_CONTENT_MISMATCH",
    "NOTE_EXISTS",
    "NOTE_UNREADABLE",
    "PATH_CODES",
    "PATH_INVALID",
    "PATH_IS_DIRECTORY",
    "PATH_MISSING",
    "PATH_NOT_REGULAR",
    "PATH_OUTSIDE_WORKSPACE",
    "PATH_SYMLINK",
    "PATH_UNREACHABLE",
    "PERCEPTION_CAPTURE_SCREEN",
    "PERCEPTION_READ_SCREEN_TEXT",
    "digest_of",
    "SpeakVerifier",
    "SpeakOnlineTool",
    "SpeakTool",
    "VOICE_UNSUPPORTED",
    "VOICE_TOOL_NAME",
    "VOICE_TIMEOUT",
    "VOICE_ONLINE_TOOL_NAME",
    "VOICE_SPEAK",
    "VOICE_SPEAK_ONLINE",
    "VOICE_FAILED",
    "VOICE_DISABLED",
    "TEXT_LANGUAGE_UNSUPPORTED",
    "TEXT_RECOGNITION_FAILED",
    "TEXT_TIMEOUT",
    "TEXT_TOOL_NAME",
    "TEXT_UNSUPPORTED",
    "ReadScreenTextTool",
    "ReadScreenTextVerifier",
    "SCREEN_CAPTURE_FAILED",
    "SCREEN_NOT_OBSERVABLE",
    "SCREEN_PERMISSION_DENIED",
    "SCREEN_STORE_FULL",
    "SCREEN_TIMEOUT",
    "SCREEN_TOOL_NAME",
    "SCREEN_UNSUPPORTED",
    "VERIFICATION_ARGUMENTS_INVALID",
    "WORKSPACE_WRITE_NOTE",
    "Capture",
    "CaptureProblem",
    "CaptureScreenTool",
    "CaptureScreenVerifier",
    "CaptureSettings",
    "CaptureStore",
    "EchoTool",
    "EchoVerifier",
    "ModelCompleteTool",
    "ModelCompleteVerifier",
    "NotIdempotentError",
    "Outcome",
    "PathProblem",
    "Retained",
    "SilentVerifierError",
    "Size",
    "Tool",
    "ToolNotFound",
    "ToolRegistry",
    "ToolsError",
    "Verifier",
    "VerifierNotFound",
    "VerifierRegistry",
    "WorkspaceSettings",
    "WriteNoteTool",
    "WriteNoteVerifier",
    "check_decision",
    "classify",
    "default_workspace_dir",
    "is_capture_name",
    "is_relative_note_path",
    "png_size",
    "node_tools",
    "production_tools",
    "production_verifiers",
    "resolve_workspace",
    "tools_v01",
    "verifiers_v01",
]
