"""The fingerprint of where a task's outcome is read, and the alarm it is (M6.3c, ADR 0054 §8).

``docs/outcomes.txt`` is derived by ``scripts/generate_outcomes.py`` from the routes whose response
model carries a task's state and from every reader of one — the functions of the pages that call
them, and those of the command line whose request has their path —, and compared byte for byte.

Every reader is answered: it renders ``halt``, and :data:`VIEWS` names the test that renders it with
every value; or the SPEC of the milestone that made it ring says why not, in «Le viste che non
dicono `halt`». A reader with neither fails here. It is an alarm, not a proof, and the file says so.
"""

from __future__ import annotations

import ast
import importlib.util
import re
import shutil
import sys
from functools import cache
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "generate_outcomes.py"
SPEC = ROOT / "docs" / "milestones" / "M6.3c.md"
WHY_NOT = "## Le viste che non dicono `halt`"
COMMAND = "uv run python scripts/generate_outcomes.py"

VIEWS: dict[str, str] = {
    "ela.api.console.summary": (
        "tests/api/test_console.py::test_the_summary_says_what_the_step_in_progress_had_done"
    ),
    "ela.api.console.home": (
        "tests/api/test_console.py::test_the_row_of_a_finished_task_says_it_too"
    ),
    "ela.api.companion.home": (
        "tests/api/test_companion.py::"
        "test_the_row_of_a_finished_task_says_what_the_step_in_progress_had_done"
    ),
    "ela.cli.tasks.run": (
        "tests/cli/test_halt.py::test_run_show_and_finished_say_what_the_step_had_done"
    ),
    "ela.cli.tasks.show": (
        "tests/cli/test_halt.py::test_run_show_and_finished_say_what_the_step_had_done"
    ),
    "ela.cli.tasks.finished": (
        "tests/cli/test_halt.py::test_run_show_and_finished_say_what_the_step_had_done"
    ),
}
"""The views that render ``halt``, each with the test that renders it with every value."""


@cache
def generator() -> ModuleType:
    """The script, loaded by path: ``scripts/`` is not a package."""
    spec = importlib.util.spec_from_file_location("generate_outcomes", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def written() -> str:
    return Path(generator().DERIVED).read_text(encoding="utf-8")


def why_not() -> dict[str, str]:
    """The lines of the SPEC that say why a reader does not render ``halt``."""
    text = SPEC.read_text(encoding="utf-8")
    section = text.split(WHY_NOT, 1)[1].split("\n## ", 1)[0]
    return dict(re.findall(r"^- `([\w.]+)` — (.+)$", section, flags=re.MULTILINE))


def test_the_fingerprint_is_what_the_generator_produces() -> None:
    """Byte for byte. A reader that came or went without an answer fails here."""
    assert Path(generator().DERIVED).read_bytes() == generator().render(), f"stale: `{COMMAND}`"


def test_it_says_of_itself_what_it_is_and_where_the_answer_goes() -> None:
    header = written()

    assert "GENERATED by scripts/generate_outcomes.py" in header
    assert "ALLARME, non una\n# dimostrazione" in header
    assert "nel documento della\n# milestone" in header
    assert (
        "uno annotato `Literal[...]` vale per i suoi valori; uno che resta `str` vale per ogni"
        in header
    )


def test_every_reader_renders_halt_or_says_why_not() -> None:
    readers = generator().readers_of(written())
    answered = set(VIEWS) | set(why_not())

    assert readers, "the fingerprint lists no reader"
    assert sorted(set(readers) - answered) == [], "a reader with no answer: write it in the SPEC"
    assert set(VIEWS).isdisjoint(why_not()), "a view cannot both render halt and say why not"


def test_every_answer_is_of_a_reader_the_fingerprint_lists() -> None:
    """The closure the other way: a view with its test, or a line of why not, of a reader that
    is not in the file any more is an answer to nothing."""
    readers = set(generator().readers_of(written()))

    assert set(VIEWS) <= readers
    assert set(why_not()) <= readers


@pytest.mark.parametrize("view", sorted(VIEWS))
def test_the_test_of_every_view_exists(view: str) -> None:
    path, name = VIEWS[view].split("::")
    tree = ast.parse((ROOT / path).read_text(encoding="utf-8"))

    assert name in {
        node.name for node in tree.body if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef)
    }


def test_the_routes_are_read_from_the_response_models() -> None:
    """The source is the routes' own types: the four of the SPEC are among them."""
    routes = {path for _, path, _ in generator().routes()}

    assert {"/tasks/{task_id}", "/tasks/finished", "/tasks/{task_id}/run", "/tasks"} <= routes


def test_a_reader_nobody_answered_makes_it_stale(monkeypatch: pytest.MonkeyPatch) -> None:
    """The failure the rule exists to produce: one reader more, and the file is stale."""
    module = generator()
    today = module.cli_readers()
    monkeypatch.setattr(module, "cli_readers", lambda: [*today, "cli ela.cli.new.view <- GET /x"])

    assert module.stale()


def test_a_derivation_that_finds_no_route_fails_instead_of_passing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The alarm of the empty derivation: a fingerprint of nothing would never fail again."""
    module = generator()
    monkeypatch.setattr(module, "carries", lambda annotation, seen=frozenset(): False)

    with pytest.raises(ValueError, match="no route carries a task's state"):
        module.routes()


def test_a_derivation_that_finds_no_reader_fails_instead_of_passing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = generator()
    monkeypatch.setattr(module, "page_readers", list)
    monkeypatch.setattr(module, "cli_readers", list)

    with pytest.raises(ValueError, match="no reader"):
        module.render()


def test_a_field_of_a_request_is_the_parameter_of_its_name_or_names_a_segment() -> None:
    matches = generator()._matches  # noqa: SLF001
    parameters = frozenset({"task_id"})

    assert matches("/tasks/{task_id}", "/tasks/{task_id}", parameters)
    assert matches("/tasks/{task_id}/{verb}", "/tasks/{task_id}/approve", parameters)
    assert matches("/tasks/{task_id}/{verb}", "/tasks/{task_id}/cancel", parameters)
    assert not matches("/tasks/{task_id}", "/tasks/finished", parameters)
    assert not matches("/tasks/{task_id}/run", "/tasks/{task_id}/cancel", parameters)
    assert not matches("/tasks", "/tasks/{task_id}", parameters)
    assert not matches("/tasks/{verb}", "/tasks/{task_id}", parameters)


def test_a_field_typed_as_a_literal_names_its_values_and_nothing_else() -> None:
    """The answer to the question of the review: a line that says a command reads a route it never
    calls is false, and a file with false lines teaches not to read it."""
    matches = generator()._matches  # noqa: SLF001
    parameters = frozenset({"task_id"})
    answers = {"verb": frozenset({"approve", "deny"})}

    assert matches("/tasks/{task_id}/{verb}", "/tasks/{task_id}/deny", parameters, answers)
    assert not matches("/tasks/{task_id}/{verb}", "/tasks/{task_id}/cancel", parameters, answers)
    assert not matches("/tasks/{task_id}/{verb}", "/tasks/{task_id}/run", parameters, answers)


def test_the_answers_of_the_command_line_read_their_two_routes_only() -> None:
    (line,) = [one for one in written().splitlines() if one.startswith("cli ela.cli.tasks.emit_")]

    assert line.split(" <- ")[1] == "POST /tasks/{task_id}/approve, POST /tasks/{task_id}/deny"


def test_the_literals_are_read_from_the_annotation_of_the_function() -> None:
    import ast

    source = "def f(a: str, verb: Literal['approve', 'deny'], one: t.Literal['x']) -> None: ...\n"
    (function,) = ast.parse(source).body
    assert isinstance(function, ast.FunctionDef)

    assert generator()._literals(function) == {  # noqa: SLF001
        "verb": frozenset({"approve", "deny"}),
        "one": frozenset({"x"}),
    }


def test_check_is_quiet_on_the_tree(capsys: pytest.CaptureFixture[str]) -> None:
    assert generator().main(["--check"]) == 0
    assert "up to date" in capsys.readouterr().out


def test_check_notices_a_fingerprint_touched_by_hand_and_never_writes(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    copy = tmp_path / "outcomes.txt"
    shutil.copy(generator().DERIVED, copy)
    copy.write_text(copy.read_text(encoding="utf-8").replace("cli ", "x ", 1), encoding="utf-8")

    assert generator().main(["--check", "--path", str(copy)]) == 1
    assert "stale" in capsys.readouterr().out
    assert "x ela.cli" in copy.read_text(encoding="utf-8"), "--check must not write"

    assert generator().main(["--path", str(copy)]) == 0
    assert not generator().stale(copy)
    assert generator().stale(tmp_path / "missing.txt")
