"""Derive the fingerprint of where a task's outcome is read (M6.3c, proposal 6; ADR 0054 §8).

``docs/outcomes.txt`` lists every **route that carries a task's state** — read from the response
models of the routes, never listed by hand — and every **reader** of one: a function of a page
module that calls one of those route functions, and a function of the command line whose request
has the path of one of those routes. Written by this script, compared **byte for byte** by
``tests/docs/test_outcomes.py`` at every ``make check``.

    uv run python scripts/generate_outcomes.py            # rewrite the fingerprint
    uv run python scripts/generate_outcomes.py --check    # exit 1 if it is stale

**What it is for.** Decision 3 of M6.3c wants the outcome of a stop said «on every surface», and a
list of surfaces written by hand is the list the first draft got wrong: it derived the views from
the routes that **already** carried ``halt``, and was silent on the views that could not say it. A
new reader stops ``make check``, and the answer goes in the document of the milestone that rang it
— the view renders ``halt`` with its test, or a line says why not.

**What it is not.** It does not prove that a view says the outcome: ``tests/docs/test_outcomes.py``
holds the views that render ``halt``, each with the test that renders it with every value, and the
lines that say why the others do not. It is an alarm, not a proof, and the file says so of itself.

Like ``generate_command_center.py`` this script **imports ``ela``** — which routes carry a task's
state is a fact of the response models, and the honest way to read it is to ask them — and reads
the page modules and the command line as source, with ``ast``: a reader is a call, not a value. It
does the derivation itself, because a script does not import from the tests.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import pkgutil
import re
import sys
import typing
from collections.abc import Iterator, Mapping, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "ela"
DERIVED = ROOT / "docs" / "outcomes.txt"
COMPOSER = "pages"
"""The module that builds a page: a module of ``api/`` that imports it **and** declares a router
serves pages (the criterion of ``page_modules()`` in ``tests/architecture/rules.py``)."""
STATE_MODEL = "TaskOut"
"""The model of a task's state on the wire; every model that holds one carries a task's state."""

HEADER = """\
# GENERATED by scripts/generate_outcomes.py — non si scrive a mano.
#
# Dove si legge l'esito di un task (M6.3c, ADR 0054 §8): le rotte il cui modello di risposta porta
# lo stato di un task, e i loro lettori — le funzioni delle pagine che le chiamano, e quelle della
# riga di comando la cui richiesta ha il percorso di una di loro. È un ALLARME, non una
# dimostrazione: dice dove l'esito si può leggere, non che lo si dica.
#
# Quando un lettore nuovo fa fallire `make check`, la risposta si scrive **nel documento della
# milestone che l'ha fatto suonare** — la vista rende `halt`, con il suo test che la rende con ogni
# valore, oppure la riga che dice perché no — e solo dopo si rigenera:
#
#     uv run python scripts/generate_outcomes.py
#
# Rigenerare e basta riporta questo file a decorazione.
#
# Un campo nel percorso di una richiesta della riga di comando vale per il parametro della rotta con
# il suo nome; uno annotato `Literal[...]` vale per i suoi valori; uno che resta `str` vale per ogni
# segmento — e allora la riga può nominare rotte che il comando non chiama.
"""


# ----------------------------------------------------------------------------------------
# The routes that carry a task's state, from their response models
# ----------------------------------------------------------------------------------------


def carries(annotation: object, seen: frozenset[object] = frozenset()) -> bool:
    """Whether a type holds a task's state: the model itself, a model with a field that holds
    one, or a container of either."""
    from pydantic import BaseModel

    if isinstance(annotation, list):  # the parameters of a Callable
        return any(carries(argument, seen) for argument in annotation)
    if annotation in seen:
        return False
    if isinstance(annotation, type) and annotation.__name__ == STATE_MODEL:
        return True
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        if any(base.__name__ == STATE_MODEL for base in annotation.__mro__):
            return True
        inner = seen | {annotation}
        return any(carries(field.annotation, inner) for field in annotation.model_fields.values())
    return any(carries(argument, seen) for argument in typing.get_args(annotation))


def route_modules() -> Iterator[object]:
    """Every module of ``ela.api`` but the entry point, which starts a server when imported."""
    import ela.api

    for found in pkgutil.iter_modules(ela.api.__path__):
        if not found.name.startswith("_"):
            yield importlib.import_module(f"ela.api.{found.name}")


def routes() -> tuple[tuple[str, str, str], ...]:
    """``(method, path, function)`` of every route whose response model carries a task's state."""
    from fastapi import APIRouter
    from fastapi.routing import APIRoute

    found: set[tuple[str, str, str]] = set()
    for module in route_modules():
        for value in vars(module).values():
            if not isinstance(value, APIRouter):
                continue
            for route in value.routes:
                if isinstance(route, APIRoute) and carries(route.response_model):
                    for method in route.methods:
                        found.add((method, route.path, route.endpoint.__name__))
    if not found:
        raise ValueError(
            "no route carries a task's state: a fingerprint of nothing would be a check that can "
            "never fail (M6.3c, the alarm of the empty derivation)"
        )
    return tuple(sorted(found, key=lambda one: (one[1], one[0])))


def functions_of_the_routes() -> frozenset[str]:
    """The names a page may call to read a task's state: the routes above, and every public
    function of a route module whose return type carries one (``answered_and_resumed``)."""
    names = {function for _, _, function in routes()}
    for module in route_modules():
        for name, value in vars(module).items():
            if name.startswith("_") or not callable(value):
                continue
            if getattr(value, "__module__", None) != getattr(module, "__name__", None):
                continue
            try:
                hints = typing.get_type_hints(value)
            except Exception:  # noqa: BLE001 — a callable without readable hints carries nothing
                continue
            if carries(hints.get("return")):
                names.add(name)
    return frozenset(names)


# ----------------------------------------------------------------------------------------
# The readers: the pages, and the command line
# ----------------------------------------------------------------------------------------


def _module_name(path: Path) -> str:
    return ".".join(("ela", *path.relative_to(SOURCE).with_suffix("").parts))


def _is_a_page_module(tree: ast.Module) -> bool:
    imports_the_composer = any(
        isinstance(node, ast.ImportFrom)
        and node.module is not None
        and (
            (node.module.endswith(".api") and any(a.name == COMPOSER for a in node.names))
            or node.module.endswith(f".api.{COMPOSER}")
        )
        for node in ast.walk(tree)
    )
    declares_a_router = any(
        isinstance(node, ast.Call)
        and (
            (isinstance(node.func, ast.Name) and node.func.id == "APIRouter")
            or (isinstance(node.func, ast.Attribute) and node.func.attr == "APIRouter")
        )
        for node in ast.walk(tree)
    )
    return imports_the_composer and declares_a_router


def _top_functions(tree: ast.Module) -> Iterator[ast.FunctionDef | ast.AsyncFunctionDef]:
    for node in tree.body:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            yield node


def page_readers() -> list[str]:
    """``page <module>.<function> <- <route functions>`` for every function of a page module that
    calls a function of the routes carrying a task's state."""
    wanted = functions_of_the_routes()
    found: list[str] = []
    for path in sorted((SOURCE / "api").glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        if not _is_a_page_module(tree):
            continue
        for function in _top_functions(tree):
            called = sorted(
                {
                    node.func.id
                    for node in ast.walk(function)
                    if isinstance(node, ast.Call)
                    and isinstance(node.func, ast.Name)
                    and node.func.id in wanted
                }
            )
            if called:
                found.append(f"page {_module_name(path)}.{function.name} <- {', '.join(called)}")
    return found


REQUEST_METHODS = {"get": "GET", "post": "POST", "put": "PUT", "delete": "DELETE"}


def _template(argument: ast.expr) -> str | None:
    """The path of a request as the code writes it: a string, or an f-string whose fields keep
    their names — ``f"/tasks/{task_id}"`` is ``/tasks/{task_id}``."""
    if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
        return argument.value
    if not isinstance(argument, ast.JoinedStr):
        return None
    parts: list[str] = []
    for value in argument.values:
        if isinstance(value, ast.Constant):
            parts.append(str(value.value))
        elif isinstance(value, ast.FormattedValue):
            parts.append("{" + ast.unparse(value.value) + "}")
    return "".join(parts)


def _matches(
    requested: str,
    path: str,
    parameters: frozenset[str],
    literals: Mapping[str, frozenset[str]] | None = None,
) -> bool:
    """Segment by segment: a literal equals a literal; a field of the request is the route's
    parameter of the same name — the names coincide (B-R8) —; a field annotated ``Literal[...]``
    names its values and nothing else; and a field that stays ``str``, whose name is no route's
    parameter, names any literal segment."""
    asked, served = requested.split("/"), path.split("/")
    if len(asked) != len(served):
        return False
    for one, other in zip(asked, served, strict=True):
        if one == other:
            continue
        field = re.fullmatch(r"\{(\w+)\}", one)
        if field is None or other.startswith("{") or field.group(1) in parameters:
            return False
        values = (literals or {}).get(field.group(1))
        if values is not None and other not in values:
            return False
    return True


def _literals(function: ast.FunctionDef | ast.AsyncFunctionDef) -> dict[str, frozenset[str]]:
    """The parameters of ``function`` annotated ``Literal["a", "b"]``, with their values."""
    found: dict[str, frozenset[str]] = {}
    for argument in [*function.args.args, *function.args.kwonlyargs]:
        annotation = argument.annotation
        if not (isinstance(annotation, ast.Subscript) and _named(annotation.value) == "Literal"):
            continue
        inner = annotation.slice
        values = inner.elts if isinstance(inner, ast.Tuple) else [inner]
        found[argument.arg] = frozenset(
            value.value
            for value in values
            if isinstance(value, ast.Constant) and isinstance(value.value, str)
        )
    return found


def _named(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    return node.attr if isinstance(node, ast.Attribute) else None


def cli_readers() -> list[str]:
    """``cli <module>.<function> <- <METHOD path>`` for every function of the command line whose
    request has the path of a route carrying a task's state."""
    served = routes()
    parameters = frozenset(
        name for _, route, _ in served for name in re.findall(r"\{(\w+)\}", route)
    )
    found: list[str] = []
    for path in sorted((SOURCE / "cli").glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for function in _top_functions(tree):
            read: set[str] = set()
            for node in ast.walk(function):
                if not (
                    isinstance(node, ast.Call)
                    and isinstance(node.func, ast.Attribute)
                    and node.func.attr in REQUEST_METHODS
                    and node.args
                ):
                    continue
                requested = _template(node.args[0])
                if requested is None:
                    continue
                method = REQUEST_METHODS[node.func.attr]
                read |= {
                    f"{method} {route}"
                    for verb, route, _ in served
                    if verb == method
                    and _matches(requested, route, parameters, _literals(function))
                }
            if read:
                found.append(
                    f"cli {_module_name(path)}.{function.name} <- {', '.join(sorted(read))}"
                )
    return found


def render() -> bytes:
    """The fingerprint as it must be on disk: the header, the routes, the readers."""
    lines = [f"route {method} {path} {function}" for method, path, function in routes()]
    readers = [*page_readers(), *cli_readers()]
    if not readers:
        raise ValueError("no reader of a task's state was found: the derivation stopped deriving")
    return (HEADER + "\n".join([*lines, *readers]) + "\n").encode("utf-8")


def readers_of(text: str) -> list[str]:
    """The readers a fingerprint lists, by name: ``<module>.<function>``."""
    return [line.split(" ")[1] for line in text.splitlines() if line.startswith(("page ", "cli "))]


def stale(path: Path = DERIVED) -> bool:
    """Whether the file on disk is not what this script produces."""
    return not path.is_file() or path.read_bytes() != render()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the fingerprint is stale")
    parser.add_argument("--path", type=Path, default=DERIVED, help="the fingerprint's file")
    arguments = parser.parse_args(argv)

    if arguments.check:
        if stale(arguments.path):
            print(
                f"{arguments.path}: stale — a reader of a task's state came or went. Write the "
                "answer in the milestone's document, then run scripts/generate_outcomes.py"
            )
            return 1
        print(f"{arguments.path}: up to date")
        return 0

    arguments.path.write_bytes(render())
    print(f"wrote {arguments.path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
