"""Derive the Command Center's fingerprint of what ELA can do (M17.2 dec. I; ADR 0044).

``apps/command-center/capabilities.txt`` is the list of the capability ids
``production_catalogue()`` builds, written by this script and compared **byte for byte** by
``tests/command_center/test_capabilities.py`` at every ``make check``.

    uv run python scripts/generate_command_center.py            # rewrite the fingerprint
    uv run python scripts/generate_command_center.py --check    # exit 1 if it is stale

**What it is for.** Fase 17 has a fixed rule — *every milestone that adds a capability adds its
view* — and a rule of process is forgotten by the first person in a hurry. This file turns it into
a failing test: a capability nobody listed makes the suite red, and the way back to green is
either the view or an explicit regeneration that somebody signs.

**What it is not.** It does not prove that any capability *has* a view, and the file says so of
itself: none of the capabilities it lists has one of its own among the four views of v1 — they
are seen sideways, in the Approval Center's question and in a task's step. It is an alarm, not a
proof.

Unlike ``generate_design_system.py``, this script **imports ``ela``**, and so does
``generate_stato.py`` before it: what it derives is a fact of the Core, and the only honest way to
read it is to ask the Core. The level of verification of everything in ``scripts/`` applies —
``ruff`` and its tests see it, ``mypy`` and the coverage gate do not.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMAND_CENTER = ROOT / "apps" / "command-center"
DERIVED = "capabilities.txt"

HEADER = """\
# GENERATED by scripts/generate_command_center.py — non si scrive a mano.
#
# L'elenco di ciò che ELA sapeva fare quando il Command Center è stato costruito: gli id delle
# capability di production_catalogue(), in ordine. È un ALLARME, non una dimostrazione — nessuna
# di queste ha una vista propria fra le quattro di v1: si vedono di riflesso, nella domanda
# dell'Approval Center e nello step di un task.
#
# Quando una capability nuova fa fallire `make check`, la risposta si scrive **nel documento
# della milestone che l'ha fatta fallire** — la vista che aggiunge, oppure la riga che dice
# perché quella capability non ne ha una — e solo dopo si rigenera:
#
#     uv run python scripts/generate_command_center.py
#
# Rigenerare e basta riporta questo file a decorazione: un file che cambia senza che nessuno
# abbia detto niente (M17.2 dec. 7 della review).
"""


def capabilities() -> tuple[str, ...]:
    """The ids of what the composition root builds, in the catalogue's own order.

    Imported here and not at the top so that ``--help`` and the tests can read this module
    without building anything, and so that the import is where the reason for it is written.
    """
    from ela.permissions.capabilities import production_catalogue

    found = tuple(spec.id for spec in production_catalogue().specs())
    if not found:
        raise ValueError(
            "production_catalogue() built no capability: a fingerprint of nothing would be a "
            "check that can never fail (M17.2 dec. I)"
        )
    return found


def render() -> bytes:
    """The fingerprint as it must be on disk: the header, then one id per line."""
    return (HEADER + "\n".join(capabilities()) + "\n").encode("utf-8")


def stale(root: Path) -> bool:
    """Whether the file on disk is not what this script produces."""
    path = root / DERIVED
    return not path.is_file() or path.read_bytes() != render()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the fingerprint is stale")
    parser.add_argument("--root", type=Path, default=COMMAND_CENTER, help="the surface's folder")
    arguments = parser.parse_args(argv)

    if arguments.check:
        if stale(arguments.root):
            print(
                f"{arguments.root / DERIVED}: stale — a capability came or went. Write the answer "
                "in the milestone's document, then run scripts/generate_command_center.py"
            )
            return 1
        print(f"{arguments.root / DERIVED}: up to date")
        return 0

    (arguments.root / DERIVED).write_bytes(render())
    print(f"wrote {arguments.root / DERIVED}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
