"""The derived files are the ones the generator produces, byte for byte (M17.1, criterio 1).

``tokens.json`` is the one source. A token changed without regenerating, or a derived file
touched by hand, fails here — and the message says the command.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from tests.design.tree import DESIGN_SYSTEM, generator

COMMAND = "uv run python scripts/generate_design_system.py"


def copy_of_the_tree(tmp_path: Path) -> Path:
    target = tmp_path / "design-system"
    shutil.copytree(DESIGN_SYSTEM, target)
    return target


def test_every_derived_file_is_what_the_generator_produces() -> None:
    rendered = generator().render_all(DESIGN_SYSTEM)
    assert set(rendered) == set(generator().DERIVED)
    for name, content in rendered.items():
        assert (DESIGN_SYSTEM / name).read_bytes() == content, f"{name} is stale: run `{COMMAND}`"


def test_a_derived_file_says_so_and_ends_its_lines_with_lf() -> None:
    for name in generator().DERIVED:
        content = (DESIGN_SYSTEM / name).read_bytes()
        assert b"GENERATED by scripts/generate_design_system.py" in content[:400], name
        assert b"\r" not in content, name
        assert content.endswith(b"\n"), name


def test_check_is_quiet_on_the_tree(capsys: pytest.CaptureFixture[str]) -> None:
    assert generator().main(["--check"]) == 0
    assert "up to date" in capsys.readouterr().out


def test_check_notices_a_token_changed_without_regenerating(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    root = copy_of_the_tree(tmp_path)
    assert generator().main(["--check", "--root", str(root)]) == 0

    source = json.loads((root / "tokens.json").read_text(encoding="utf-8"))
    source["space"]["4"]["$value"] = "1.125rem"
    (root / "tokens.json").write_text(json.dumps(source), encoding="utf-8")

    assert generator().main(["--check", "--root", str(root)]) == 1
    assert "tokens.css" in capsys.readouterr().out


def test_check_notices_a_derived_file_touched_by_hand(tmp_path: Path) -> None:
    root = copy_of_the_tree(tmp_path)
    page = root / "index.html"
    page.write_bytes(page.read_bytes().replace(b"Design System", b"Design  System", 1))

    assert generator().stale(root) == ["index.html"]


def test_check_never_writes_and_a_run_repairs(tmp_path: Path) -> None:
    root = copy_of_the_tree(tmp_path)
    (root / "tokens.css").write_bytes(b"/* by hand */\n")

    assert generator().main(["--check", "--root", str(root)]) == 1
    assert (root / "tokens.css").read_bytes() == b"/* by hand */\n"

    assert generator().main(["--root", str(root)]) == 0
    assert generator().stale(root) == []


def test_a_missing_derived_file_is_stale(tmp_path: Path) -> None:
    root = copy_of_the_tree(tmp_path)
    (root / "specimen-switch.css").unlink()

    assert generator().stale(root) == ["specimen-switch.css"]
